[package]
name = "imleak"
description = "Immutable data structures not GC'd"
version = "0.1.0"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
rand = "0.8"
