version: 2
jobs:
  build:
    docker:
      - image: rust
    steps:
      - checkout
      - run: rustup default nightly-2019-07-02
      - run: rustup component add clippy rustfmt
      - run: cargo build
      - run: cargo fmt -- --check
      - run: cargo clippy
      - run: cargo test
      - run: cargo bench
