version: 2
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run: rustup component add clippy rustfmt
      - run: cargo build
      - run: cargo fmt -- --check
      - run: cargo clippy
      - run: cargo test
      - run: cargo bench
